# Alumno

*Sustituid esta frase por vuestros nombres y apellidos.*

# Ejercicios de Pandas

Antes de empezar, importemos los módulos que vamos a utilizar.

In [1]:
import numpy as np
import pandas as pd

## Series

### Asigna el nombre "alfabeto" a la siguiente serie e imprímela.

Pista: [pandas.Series.name](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.name.html)

In [2]:
s = pd.Series(list('abcedfghijklmnopqrstuvwxyz'))
s.head()

0    a
1    b
2    c
3    e
4    d
dtype: object

In [4]:
# Solución
s.name = "alfabeto"
print(s.head())

0    a
1    b
2    c
3    e
4    d
Name: alfabeto, dtype: object

### Escribe una expresión que, dadas dos series, diga si todos los elementos de la primera son mayores que los correspondientes de la segunda.

Pista: [pandas.Dataframe.all()](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.DataFrame.all.html)

In [7]:
s1 = pd.Series(np.random.randint(1, 10, size=10))
s2 = s1 + 1

In [8]:
# Solución
(s1 > s2).all()

np.False_

### Escribe una expresión que, dadas dos series, diga si hay algún elemento de la primera es menor o igual que el correspondiente de la segunda.

Pista: [pandas.Dataframe.any()](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.DataFrame.any.html)

In [12]:
s1 = pd.Series(np.random.randint(1, 10, size=10))
s2 = pd.Series(np.random.randint(1, 10, size=10))

In [13]:
# Solución
(s1 <= s2).any()

np.True_

### Extrae todos los elementos de la serie dada que se encuentran en las posiciones indicadas por una lista.

In [14]:
serie = pd.Series(list('abcdefghijklmnopqrstuvwxyz'))
posicion = [0, 4, 8, 14, 20]

In [15]:
# Solución
serie.iloc[posicion]

0     a
4     e
8     i
14    o
20    u
dtype: object

### Construye una serie que sea el resultado de concatenar a una serie dada los elementos de otra.

Muestra el resultado de concatenar `s1` y `s2`, y responde a estas preguntas: ¿Qué ha sucedido con el índice? ¿Cuál es el tipo de datos de la serie resultante? ¿Qué sucede si indexamos la serie con el índice `0`?

Pista: [pandas.concat](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.concat.html)

In [16]:
s1 = pd.Series(range(5))
s2 = pd.Series([0.2, 0.3, 0.4])

In [ ]:
# Solución y respuestas a las preguntas
resultado = pd.concat([s1, s2])
print(resultado)

# ¿Qué ha sucedido con el índice?
# Se han mantenido los índices originales de ambas series. Ahora los indices
# 0, 1 y 2 están duplicados

# ¿Cuál es el tipo de datos de la serie resultante? 
# float64, pandas convierte los enteros de s1 para acomodar los decimales de s2

0    0.0
1    1.0
2    2.0
3    3.0
4    4.0
0    0.2
1    0.3
2    0.4
dtype: float64

In [20]:
# ¿Qué sucede si indexamos la serie con el índice 0?
resultado.loc[0]

0    0.0
0    0.2
dtype: float64

In [ ]:
# Al haber indices duplicados, resultado.loc[0] devuelve una serie con 
# los valores que comparten ese indice:
# 0 de s1 y 0.2 de s2

### Ordena una serie, primero por el valor del índice y después por el valor de la serie, e imprímelas.

Pistas: [pandas.Series.sort_index()](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.sort_index.html) y [pandas.Series.sort_values()](https://pandas.pydata.org/docs/reference/api/pandas.Series.sort_values.html)

In [21]:
serie = pd.Series({3: 1, 5: 0, 1: 4})
print(serie)

3    1
5    0
1    4
dtype: int64

In [23]:
# Solución

print("Serie ordenada por índice")
print(serie.sort_index())

print("Serie ordenada por valor")
print(serie.sort_values())

Serie ordenada por índice
1    4
3    1
5    0
dtype: int64
Serie ordenada por valor
5    0
3    1
1    4
dtype: int64

### Calcula la media del error cuadrático entre dos series.

Nota: La fórmula del error cuadrático entre $x$ e $y$ es $(x - y)^2$.

In [24]:
np.random.seed(0)
x = pd.Series(range(10))
y = pd.Series(range(10)) + np.random.random(10)
print(x)
print(y)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    0.548814
1    1.715189
2    2.602763
3    3.544883
4    4.423655
5    5.645894
6    6.437587
7    7.891773
8    8.963663
9    9.383442
dtype: float64

In [27]:
# Solución

((x-y)**2).mean()

np.float64(0.41319910235287544)

### Convierte la siguiente serie de fechas introducidas como cadenas a una serie de tipo `datetime` llamada `fechasdt`. 

Pista: [pandas.to_datetime()](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.to_datetime.html)

In [26]:
fechas = pd.Series(['02 Jan 2010T00:00:01',
                    '02-02-2011',
                    '20120303',
                    '2013/04/04',
                    '2014-05-05',
                    '2015-06-06T12:20'])

In [29]:
# Solución

fechasdt = pd.to_datetime(fechas, format='mixed')
print(fechasdt)

0   2010-01-02 00:00:01
1   2011-02-02 00:00:00
2   2012-03-03 00:00:00
3   2013-04-04 00:00:00
4   2014-05-05 00:00:00
5   2015-06-06 12:20:00
dtype: datetime64[ns]

### Crea tres series a partir de la serie `fechasdt` anterior llamadas `days`, `months` y `years`, donde cada una contenga el día, el mes y el año de cada fecha, respectivamente.

Pista: Una serie del tipo `datetime` tiene un atributo `.dt` con métodos para acceder al día, mes y año, por ejemplo, [pandas.Series.dt.day()](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.Series.dt.day.html).

In [31]:
# Solución

days = fechasdt.dt.day

print("Días:\n", days)

months = fechasdt.dt.month

print("Meses\n", months)

years = fechasdt.dt.year

print("Días:\n", years)

Días:
 0    2
1    2
2    3
3    4
4    5
5    6
dtype: int32
Meses
 0    1
1    2
2    3
3    4
4    5
5    6
dtype: int32
Días:
 0    2010
1    2011
2    2012
3    2013
4    2014
5    2015
dtype: int32

### Crea una serie con valores aleatorios enteros entre 1 y 10, pero cuyo índice tenga 12 objetos del tipo `datetime` con el primer día de cada mes del año 2024

El índice deben empezar por el **01-01-2024** y terminar en el **01-12-20243**.

Pistas: [numpy.random.randint](https://numpy.org/doc/stable/reference/random/generated/numpy.random.randint.html()) y [pandas.date_range()](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.date_range.html)

In [33]:
# Solución

indices = pd.date_range(start='2024-01-01', end='2024-12-01', freq='MS') #MS es moth start
serie_mensual = pd.Series(np.random.randint(1, 11, size=12), index=indices)

print(serie_mensual)

2024-01-01    4
2024-02-01    6
2024-03-01    1
2024-04-01    3
2024-05-01    4
2024-06-01    9
2024-07-01    2
2024-08-01    4
2024-09-01    4
2024-10-01    4
2024-11-01    8
2024-12-01    1
Freq: MS, dtype: int64

## DataFrames

### Dadas las siguientes series que representan frutas, precio y peso comprado de cada una de ellas, construye un `Dataframe` y obtén tanto el precio medio como el peso medio de cada tipo de fruta.

Pista: [pandas.Series.groupby()](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.Series.groupby.html)

In [34]:
np.random.seed(0)
frutas = pd.Series(np.random.choice(['manzana', 'banana', 'zanahoria'], 10))
precios = pd.Series(np.random.sample(10) * 3)
pesos = pd.Series(np.random.randint(1, 5, 10))

print(frutas.tolist())
print(precios.tolist())
print(pesos.tolist())

['manzana', 'banana', 'manzana', 'banana', 'banana', 'zanahoria', 'manzana', 'zanahoria', 'manzana', 'manzana']
[0.8179688837403396, 1.4329953519640495, 2.4365061863264796, 1.439931517125172, 1.1783543883024892, 2.5082362906121327, 1.0121884812518052, 1.9445156161535917, 1.1047246195216438, 2.871465476859139]
[4, 4, 1, 3, 4, 1, 2, 4, 2, 4]

In [35]:
# Solución

df_frutas = pd.DataFrame({'fruta': frutas, 'precio': precios, 'peso': pesos})
print(df_frutas.groupby('fruta').mean())

             precio      peso
fruta
banana     1.350427  3.666667
manzana    1.648571  2.600000
zanahoria  2.226376  2.500000

### Crea un `DataFrame` a partir del archivo `planets.csv` seleccionando solamente las columnas `method`,  `year` y `distance`, y calcula el número elementos que tiene.

Pista: [pandas.read_csv](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html)

In [39]:
# Solución

planetas = pd.read_csv('data/planets.csv')[['method', 'year', 'distance']]
print("Numero de elementos = ", len(planetas))

Numero de elementos =  1035

### Calcula cuantos planetas se han descubierto usando cada método de detección a partir del *dataset* de planetas anterior.

In [40]:
# Solución

planetas.groupby('method').size()

method
Astrometry                         2
Eclipse Timing Variations          9
Imaging                           38
Microlensing                      23
Orbital Brightness Modulation      3
Pulsar Timing                      5
Pulsation Timing Variations        1
Radial Velocity                  553
Transit                          397
Transit Timing Variations          4
dtype: int64

### Determina en qué año se descubrieron más planetas a partir del *dataset* de planetas anterior.

In [41]:
# Solución

planetas.groupby('year').size().idxmax()

np.int64(2011)

In [ ]:
# en el año 2011

### Create un `DataFrame` a partir del *dataset* de coches [Cars93_miss.csv](https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv), y encuentra el fabricante, modelo, tipo y precio del coche más caro (solamente deben devolverse esas columnas).

En primer lugar, crea el dataset a partir de la URL anterior:

In [45]:
# Solución

df_coches = pd.read_csv('https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv')

Luego, muestra el precio del coche más caro, para lo cual puedes usar [pandas.DataFrame.max()](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.DataFrame.max.html):

In [47]:
# Solución


precio_max = df_coches['Price'].max()

print(precio_max)

61.9

A continuación, genera una serie de valores booleanos con el resultado de la comparación con dicho precio:

In [49]:
# Solución

mascara_max = df_coches['Price'] == precio_max

A partir de la expresión anterior, obtén la fila del dataframe que cumple la condición de precio máximo con [pandas.DataFrame.loc()](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.DataFrame.loc.html):

In [50]:
# Solución


fila_cara = df_coches.loc[mascara_max]

Por último, selecciona únicamente las columnas del dataframe indicadas (fabricante, modelo, tipo, precio):

In [51]:
# Solución


fila_cara[['Manufacturer', 'Model', 'Type', 'Price']]

     Manufacturer Model     Type  Price
58  Mercedes-Benz  300E  Midsize   61.9

### Calcula una nueva columna `Norm.price` en el *dataset* de coches anterior con el precio normalizado con respecto a su valor máximo y mínimo ().

Nota: Esta normalización se realiza con la siguiente operación: $(precio - precioMinimo)/(precioMaximo - precioMinimo)$

In [56]:
# Solución

df_coches['Norm.price'] = (df_coches['Price'] - df_coches['Price'].min()) / (df_coches['Price'].max() - df_coches['Price'].min())
print(df_coches[['Norm.price', 'Price']])

    Norm.price  Price
0     0.155963   15.9
1     0.486239   33.9
2     0.398165   29.1
3     0.555963   37.7
4     0.414679   30.0
..         ...    ...
88    0.225688   19.7
89    0.231193   20.0
90    0.291743   23.3
91    0.280734   22.7
92    0.354128   26.7

[93 rows x 2 columns]

### Encuentra los tres vehículos con mayor precio (`Price`), ignorando los que no tengan precio asignado (NaN), en el *dataset* de coches anterior.

Pista: Averigua para qué sirve el parámetro `subset` de [pandas.DataFrame.dropna()](https://pandas.pydata.org/pandas-docs/version/1.5/reference/api/pandas.DataFrame.dropna.html).

In [57]:
# Solución

df_coches.dropna(subset=['Price']).sort_values('Price', ascending=False).head(3)

,Manufacturer,Model,Type,Min.Price,Price,Max.Price,MPG.city,MPG.highway,AirBags,DriveTrain,...,Length,Wheelbase,Width,Turn.circle,Rear.seat.room,Luggage.room,Weight,Origin,Make,Norm.price
58,Mercedes-Benz,300E,Midsize,43.8,61.9,80.0,19.0,25.0,Driver & Passenger,Rear,...,NaN,110.0,69.0,37.0,NaN,15.0,3525.0,non-USA,Mercedes-Benz 300E,1.000000
47,Infiniti,Q45,Midsize,45.4,47.9,NaN,17.0,22.0,NaN,Rear,...,200.0,113.0,72.0,42.0,29.0,15.0,4000.0,non-USA,Infiniti Q45,0.743119
10,Cadillac,Seville,Midsize,37.5,40.1,42.7,16.0,25.0,Driver & Passenger,Front,...,204.0,111.0,74.0,44.0,31.0,NaN,3935.0,USA,Cadillac Seville,0.600000

### Crea un `DataFrame` a partir del archivo `california_cities.csv` y muestra la población total de la ciudad con más habitantes (se deben mostrar las columnas `city` y `population_total`).

In [58]:
# Solución

ciudades = pd.read_csv('data/california_cities.csv')
ciudades.loc[ciudades['population_total'].idxmax(), ['city', 'population_total']]

city                LosAngeles
population_total       3884307
Name: 239, dtype: object

### Determina cuál es la población de la ciudad más septentional de California a partir del *dataset* de ciudades anterior (se deben mostrar las columnas `city`, `latd` y `population_total`).

In [60]:
# Solución

ciudades.loc[ciudades['latd'].idxmax(), ['city', 'latd', 'population_total']]

city                Dorris
latd                41.965
population_total       939
Name: 114, dtype: object

### Calcula la densidad de población de la ciudad de California que se encuentra a mayor altitud a partir del *dataset* de ciudades anterior (se deben mostrar las columnas `city`, `elevation_m` y `area_total_km2`, así cómo la densidad de población total en habitantes por kilómetro cuadrado)

In [63]:
# Solución

idx_max_elev = ciudades['elevation_m'].idxmax()

#Calculo su densidad y la guardo en una nueva columna solo para esa fila
ciudades.loc[idx_max_elev, 'densidad_pob'] = ciudades.loc[idx_max_elev, 'population_total'] / ciudades.loc[idx_max_elev, 'area_total_km2']

#Resultado
ciudades.loc[idx_max_elev, ['city', 'elevation_m', 'area_total_km2', 'densidad_pob']]

city              MammothLakes
elevation_m             2402.0
area_total_km2          65.541
densidad_pob        125.631284
Name: 246, dtype: object